sudo: false
language: ruby
addons:
  code_climate:
    repo_token: 48739096f72763cbed9bd407efd2ed33151ce5663fb3181455128f06d6123ef3

before_install:
  - gem install bundler
  - gem update bundler

bundler_args: --without development

script: bundle exec rspec

matrix:
  include:
    - rvm: 2.4.1
    - rvm: 2.3.4
    - rvm: 2.2.7
    - rvm: jruby-9.1.13.0
      env: JRUBY_OPTS="--server -J-Xms1500m -J-Xmx1500m -J-XX:+UseConcMarkSweepGC -J-XX:-UseGCOverheadLimit -J-XX:+CMSClassUnloadingEnabled"
      jdk: oraclejdk8
